easy_admin:
    #Global Settings
    site_name: 'Century Challenge Admin Page'
    
    design:
    # this is the default form theme used by backends
        form_theme: '@EasyAdmin/form/bootstrap_4.html.twig'
    # these custom templates are applied to all entities
        brand_color: '#1ABC9C'
        menu:
            - { label: 'Public Homepage', route: 'homepage', icon: 'home' }
            - { entity: 'User', icon: 'user' }
            - { entity: 'Ride' }
    show:
        max_results: 10
            
    list:
        actions:
            - { name: 'edit', icon: 'pencil'}
            - { name: 'delete', icon: 'trash'}
        # allow deleting multiple items at once ...
        batch_actions: ['delete']
    
    #Per entity settings
    entities:
        User:
            class: App\Entity\User
            label: 'Users'
            disabled_actions: ['new']
            list:
                title: '%%entity_label%% listing'
                fields:
                      - 'id'
                      - 'username'
                      - 'name'
                      - { property: 'email', type: 'email' }
                      - { property: 'stravaID', label: 'Strava ID' }
            form:
                fields:
                      - { property: 'id', type_options: { disabled: true } }
                      - 'username'
                      - 'name'
                      - { property: 'email', type: 'email', type_options: { trim: true } }
                      - { property: 'stravaID', label: 'Strava ID' }
                actions:
                      - { name: 'delete' }
                      - { name: 'list', label: 'Return to list' }
            show:
                title: '%%entity_label%% (#%%entity_id%%)'
                fields: ['id', 'name', 'username', 'email', { property: 'stravaID', label: 'Strava ID' }, { property: 'rides'}]
            edit:
                title:  'Edit %%entity_label%% (#%%entity_id%%)'
                fields:
                      - passwordRequestToken
                      - requestTokenExpiry

        Ride:
            class: App\Entity\Ride
            label: 'Ride'
            list:
                title: '%%entity_label%% listing'
                fields:
                      - 'id'
                      - { property: 'user', label: 'Name' }
                      - { property: 'km', label: 'KM' }
                      - { property: 'average_speed', label: 'Average Speed' }
                      - { property: 'date', label: 'Date' }
                      - { property: 'date_added', label: 'Date Added' }
            form:
                fields:
                      - { property: 'user', label: 'Name', type_options: { disabled: true } }
                      - { property: 'km', label: 'KM' }
                      - { property: 'average_speed', label: 'Average Speed' }
                      - { property: 'date', label: 'Date' }
                      - { property: 'date_added', label: 'Date Added' }
                      - { property: 'details', label: 'Details' }
                      - { property: 'strava_ride_id', label: 'Strava ID' }
                      - { property: 'club_ride', label: 'Club Ride' }
                actions:
                      - { name: 'delete'}
                      - { name: 'list', label: 'Return to list'}
            show:
                title: '%%entity_label%% (#%%entity_id%%)'
                fields: ['id', 'user', { property: 'km', label: 'KM' }, { property: 'average_speed', label: 'Average Speed' }, 'date', 'date_added', 'details', { property: 'strava_ride_id', label: 'Strava Ride ID' }, 'club_ride']
            new:
                title: 'Add Ride'
                fields:
                      - { property: 'user', label: 'Name', type_options: { disabled: false } }
            edit:
                title:  'Edit %%entity_label%% (#%%entity_id%%)'
