  
---
distFolder: ./
setup:
  - name: Setup composer
    action: php-actions/composer@v6
    properties:
      args: --optimize-autoloader
  - name: Make envfile
    action: fmunirdev/envvar-to-dotenv-action@v0.2.0
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      STRAVA_SECRET: ${{ secrets.STRAVA_SECRET }}
      STRAVA_ID: ${{ secrets.DATABASESTRAVA_ID_URL }}
      KOMOOT_SECRET: ${{ secrets.KOMOOT_SECRET }}
      KOMOOT_ID: ${{ secrets.KOMOOT_ID }}
      MAILER_DSN: ${{ secrets.MAILER_DSN }}
      MAILER_FROM: ${{ secrets.MAILER_FROM }}
    properties:
      variableNames: APP_ENV,APP_SECRET,APP_DEBUG,DATABASE_URL,STRAVA_SECRET,STRAVA_ID,KOMOOT_SECRET,KOMOOT_ID,MAILER_DSN,MAILER_FROM
      target: .env.local
build:
  name: Build assets and run tests
  # commands that are executed one after the other at the build servers NOT at real webspace
  # php .deploy-now/create-app-secret = call of a little PHP script which creates and sets APP_SECRET to .env.local
  command:
    php .deploy-now/create-app-secret;
    #php ./vendor/bin/phpunit;