---
distFolder: ./
setup:
  - name: Make envfile
    action: fmunirdev/envvar-to-dotenv-action@v0.2.0
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      STRAVA_SECRET: ${{ secrets.STRAVA_SECRET }}
      STRAVA_ID: ${{ secrets.STRAVA_ID }}
      KOMOOT_SECRET: ${{ secrets.KOMOOT_SECRET }}
      KOMOOT_ID: ${{ secrets.KOMOOT_ID }}
      MAILER_DSN: ${{ secrets.MAILER_DSN }}
      MAILER_FROM: ${{ secrets.MAILER_FROM }}
    properties:
      variableNames: APP_ENV,APP_SECRET,APP_DEBUG,DATABASE_URL,STRAVA_SECRET,STRAVA_ID,KOMOOT_SECRET,KOMOOT_ID,MAILER_DSN,MAILER_FROM
      target: .env.local
  - name: Setup composer
    action: php-actions/composer@v6
    properties:
      args: --no-dev --optimize-autoloader
  - name: Optimise composer
    action: php-actions/composer@v6
    properties:
      command: dump-autoload
      args: --optimize --no-dev --classmap-authoritative
#  - name: Setup Node.js v14.x
#    action: actions/setup-node@v1
#    properties:
#      node-version: 14.x
#prepare:
#  name: Prepare project environment
  # here you can decide to run npm ci or npm install or remove the "prepare"
  # part if you don't create assets with node/Symfony Encore
#  command: npm ci
build:
  name: Build assets and run tests
  # commands that are executed one after the other at the build servers NOT at real webspace
  # php .deploy-now/create-app-secret = call of a little PHP script which creates and sets APP_SECRET to .env.local
  command:
#    npm run build;
    php .deploy-now/create-app-secret;