name: Deploy Now

on:
  - push
  - workflow_dispatch

jobs:
  deploy-now:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1
        id: project
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          project: ${{ secrets.IONOS_PROJECT_ID }}
          service-host: api-eu.ionos.space
      - name: checkout
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup composer
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: php-actions/composer@v6
        with:
          args: --optimize-autoloader
      - name: Make envfile
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: fmunirdev/envvar-to-dotenv-action@v0.2.0
        with:
          target: .env.local
          variableNames: APP_ENV,APP_SECRET,APP_DEBUG,DATABASE_URL,STRAVA_SECRET,STRAVA_ID,KOMOOT_SECRET,KOMOOT_ID,MAILER_DSN,MAILER_FROM
        env:
          APP_DEBUG: 0
          APP_ENV: prod
          DATABASE_URL: mysql://dbu1601154:9GjyXbEgm!mUZ4m@db5006074270.hosting-data.io:3306/dbs5086305
          KOMOOT_ID: centurychallenge-gvwb9t
          KOMOOT_SECRET: ud3iethoot9ol2pio4eihooyi
          MAILER_DSN: smtp://cc@leicesterforest.com:r4UycX5ZcwhpU@smtp.ionos.co.uk:587
          MAILER_FROM: cc@leicesterforest.com
          STRAVA_ID: 31826
          STRAVA_SECRET: abc43fbc0316bded6a4acf570c56c0f86eddb8f5
      - name: Build assets and run tests
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        run: php .deploy-now/create-app-secret;
      - name: Deploy build
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: ionos-deploy-now/deploy-to-ionos-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          bootstrap-deploy: ${{ steps.project.outputs.bootstrap-deploy }}
          branch-id: ${{ steps.project.outputs.branch-id }}
          dist-folder: ./
          project: ${{ secrets.IONOS_PROJECT_ID }}
          remote-host: ${{ steps.project.outputs.remote-host }}
          service-host: api-eu.ionos.space
          storage-quota: ${{ steps.project.outputs.storage-quota }}
